
services:
  server:
    build: .
    env_file:
      - env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: go run ./main.go #-b 0.0.0.0
  db:
    env_file:
      - env
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: